spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521/XEPDB1
    username: test1
    password: 1234
    driver-class-name: oracle.jdbc.OracleDriver

mybatis:
  mapper-locations: classpath:/mappers/**/*.xml
  type-aliases-package: com.example.blobtest.file.entity
  configuration:
    map-underscore-to-camel-case: true

server:
  port: 8080

# 파일 업로드 제한
spring.servlet.multipart:
  max-file-size: 10MB
  max-request-size: 10MB
